---
environments:
  prod:
    include:
      - prod_hosts.yml
      - path: common.yml
        key: all/vars
      - prod_groupvars.yml
      - path: windows.yml
        key: windows/vars
      - path: prod_hostvars.yml
        key: _meta/hostvars
      - path: vault.yml
        key: all/vars
  dev:
    include:
      - dev_hosts.yml
      - path: common.yml
        key: all/vars
      - dev_groupvars.yml
      - path: dev_hostvars.yml
        key: _meta/hostvars
