---
environments:
  prod:
    include:
      - prod_hosts.yml
      - common.yml
      - prod_groupvars.yml
#      - path: windows.yml
#        key: windows/vars
      - path: prod_hostvars.yml
        key: _meta/hostvars
  dev:
    include:
      - dev_hosts.yml
      - common.yml
      - dev_groupvars.yml
      - path: dev_hostvars.yml
        key: _meta/hostvars
