language: python
python:
- '2.7'
- '3.6'
install:
- python setup.py install
- pip install coverage
script:
- coverage run --source=aggravator setup.py test
- coverage report -m
deploy:
  provider: pypi
  user: petercb
  password:
    secure: m4bycCo30zOLJQQqHbZo6ffGcHZWMJRmdkY+MGYhvPUa1iLVmJ3uJ/12lQ8EYlU4tmeiq9K6Og6zmKBg0muN2MtVIdYpzHzHBJmMvw7i2HJRVV0wkGq1H6rtZdvZo/2wKCVjoMDr5ag7Mrs2rn0pa/495tEUdX/YnKfCkONkibTjeGLfLIQmYYOhhaTKcDI2ldIInamG2q850UEQHJHaFV7sBJc58Ox8cxVe+aOeh8yJPve4rV+9n+RFg4pH6W6LrBixZQSl1bbf5UQ3A1l5V8TLuy7IEBFGRPvOkF+s1t5IL95IQvvz1TyUUpBfOslXyYVv45LNu2O+vURXVhj8IZSEGrqs8L6nAWVXsaE2FaRwCD9qwycwuIRqKO84VYsCjK/vsgxjBEopWLpFKVEnn9fg4f7NLp2XHc9kO+PJiUpO/sGBzdfOSKGhaGGFVTt9mB1hyuE8VNQQi/jXUT9QqGaRueYfHOi7oLxuF3OYiXF4nu7OmEpIaZqqWChyR+v1VpSNM/NywCCtt1cyTf0w1Di0wjgpiBR8il4pL31+NWdKlJGoIanmb5VMn+HM8IWhomzvECoVU52LPgui+1iDLJO11rkSdaM2gFkKyKhHrLW+5FH2IHLxV5IvRsIHd2Cg3zWUiQkl9KM5Zdat/pIGHNCjbJ5wYDjyxEF0IZBgYgs=
  on:
    tags: true
