language: python
python:
  - "2.7"
addons:
  apt:
    packages:
      - jq
install:
  - python setup.py install
script:
  - inventory --uri=example/config.yml --env=prod --list > output.json
  - jq -S . output.json
